### ISSUE TITLE
Verbesserungen

### ISSUE THREAD

**Issue by clariion** [ramy-zemo/Willhaben-Grabber#2]
Hi,

konnte dich bei Discord nicht finden. Schreibe es deswegen hier.

Das Programm würde ich gern auf einem Rechner 24/7 laufen lassen. Bin auf der Suche nach einer Wohnung.

Telegram Bot integrieren, sobald eine neue Anzeige veröffentlicht ist, dass man eine Telegram Nachricht bekommt.
Intervalle für die "Checks" setzen können, alle 10 Sek, 15 Sek, 30 Sek..usw

Würde dir einen grünen Schein spenden. Später wahrscheinlich noch mehr. :)

LG

**Comment by ramyodev** [comment]
Hallo,
ja mein Discord Tag hat sich geändert.

Die von dir gewünschten Änderungen kann ich gerne umsetzen. Schreib mir gerne auf Disord:Ramo#3735

Lg Ramo
